name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request: {}
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        workspace:
          - ember-simple-auth
          - classic-test-app
          - test-app

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - uses: volta-cli/action@25888009cd70dbe17a140f1c56d93f8c09f7bcef # tag=v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: lint
        run: yarn workspace ${{ matrix.workspace }} lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        workspace:
          - ember-simple-auth
          - classic-test-app
          - test-app
        test-suite:
          - test:one ember-lts-3.12
          - test:one ember-lts-3.16
          - test:one ember-lts-3.20
          - test:one ember-lts-3.24
          - test:one ember-lts-3.28
          - test:one ember-4.0
          - test:one ember-lts-4.4
          - test:one ember-lts-4.8
          - test:one ember-default
        allow-failure: [false]
        include:
          - workspace: ember-simple-auth
            test-suite: "test:one ember-beta"
            allow-failure: true
          - workspace: test-app
            test-suite: "test:one ember-beta"
            allow-failure: true
          - workspace: classic-test-app
            test-suite: "test:one ember-beta"
            allow-failure: true
          - workspace: ember-simple-auth
            test-suite: "test:one ember-release"
            allow-failure: true
          - workspace: test-app
            test-suite: "test:one ember-release"
            allow-failure: true
          - workspace: classic-test-app
            test-suite: "test:one ember-release"
            allow-failure: true
          - workspace: ember-simple-auth
            test-suite: "test:one embroider-safe"
            allow-failure: false
          - workspace: ember-simple-auth
            test-suite: "test:one embroider-optimized"
            allow-failure: false

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - uses: volta-cli/action@25888009cd70dbe17a140f1c56d93f8c09f7bcef # tag=v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: tests
        run: yarn workspace ${{ matrix.workspace }} ${{ matrix.test-suite }}
        continue-on-error: ${{ matrix.allow-failure }}

  extra-tests:
    name: Tests (Floating Dependenies)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        workspace:
          - ember-simple-auth
          - classic-test-app
          - test-app

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - uses: volta-cli/action@25888009cd70dbe17a140f1c56d93f8c09f7bcef # tag=v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install --no-lockfile

      - name: tests
        run: yarn workspace ${{ matrix.workspace }} test
        continue-on-error: true

  node-tests:
    name: Node Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - uses: volta-cli/action@25888009cd70dbe17a140f1c56d93f8c09f7bcef # tag=v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: tests
        run: yarn workspace ember-simple-auth test:node
